import rule from '../../../src/rules/structure/layers'
import { fixtureRuntime, runtime, tsTester } from '../../utils'

tsTester.run('layers', rule, {
  valid: [
    { filename: runtime('app/composables/useBrunch.ts'), code: `import { BrunchQuery } from '../../shared/tokens/Brunch'` },
    { filename: runtime('server/orchestr/ticketing/Order.query.ts'), code: `import { fetchOrders } from '../../utils/ticketing/orders'` },
    { filename: runtime('server/orchestr/ticketing/Order.query.ts'), code: `import { defineTicketApi } from '../../middleware/ticketApi'` },
    { filename: runtime('server/orchestr/ticketing/Order.query.ts'), code: `import { mapAsset } from '../../utils/mapAsset'` },
    { filename: fixtureRuntime('server/orchestr/vouchers/Voucher.query.ts'), code: `import { track } from '../../utils/tracking/track'` },
    { filename: fixtureRuntime('server/utils/vouchers/context.ts'), code: `import { price } from '../product/price'`, options: [{ sharedDomains: ['product'] }] },
    { filename: runtime('server/utils/ticketing/orders.ts'), code: `import type { TicketApi } from '../../client/ticketApi'` },
    { filename: runtime('server/utils/ticketing/orders.ts'), code: `import { type TicketApi } from '../../client/ticketApi'` },
    { filename: runtime('server/utils/ticketing/orders.ts'), code: `import type { Identity } from '../../middleware/identity'` },
    { filename: runtime('server/utils/vouchers/cart.ts'), code: `import type { Order } from '../ticketing/orders'` },
    { filename: runtime('server/api/tickets/status.get.ts'), code: `import { createTicketApi } from '../../client/ticketApi'` },
    { filename: runtime('server/media-libraries/shopware.ts'), code: `import { defineShopware } from '../middleware/shopware'` },
    { filename: runtime('server/middleware/identity.ts'), code: `import { createUnidyClient } from '../client/unidy'` },
    { filename: runtime('server/orchestr/ticketing/Order.query.test.ts'), code: `import handler from './Order.query'` },
    { filename: runtime('app/utils/openingHours.ts'), code: `import type { Status } from '../components/LocationCard.vue'` },
    { filename: runtime('app/plugins/options.ts'), code: `import type { ModuleOptions } from '../../../module'` },
    { filename: runtime('server/utils/hash.ts'), code: `import { createHash } from 'node:crypto'` },
    { filename: runtime('shared/models/buffer.ts'), code: `import type { Buffer } from 'node:buffer'` },
    { filename: runtime('app/components/Card.ts'), code: `import { ref } from 'vue'` },
    { filename: runtime('app/sections/SectionCards.ts'), code: `import BlockCard from '../blocks/BlockCard.vue'` },
    { filename: '/app/src/module.ts', code: `import handler from './runtime/server/orchestr/Brunch.query'` },
  ],

  invalid: [
    { filename: runtime('app/composables/useOrder.ts'), code: `import { orders } from '../../server/utils/orders'`, errors: [{ messageId: 'appImportsServer' }] },
    { filename: runtime('app/composables/useOrder.ts'), code: `import type { Order } from '../../server/utils/orders'`, errors: [{ messageId: 'appImportsServer' }] },
    { filename: runtime('app/composables/useOrder.ts'), code: `export { orders } from '../../server/utils/orders'`, errors: [{ messageId: 'appImportsServer' }] },
    { filename: runtime('app/composables/useOrder.ts'), code: `const utils = await import('../../server/utils/orders')`, errors: [{ messageId: 'appImportsServer' }] },
    { filename: runtime('server/utils/cards.ts'), code: `import Card from '../../app/components/Card.vue'`, errors: [{ messageId: 'serverImportsApp' }] },
    { filename: runtime('shared/tokens/Order.ts'), code: `import { orders } from '../../server/utils/orders'`, errors: [{ messageId: 'sharedImportsSide', data: { side: 'server' } }] },
    { filename: runtime('app/plugins/cropper.ts'), code: `import { setup } from '../../../setup/cropper'`, errors: [{ messageId: 'runtimeImportsBuild' }] },
    { filename: runtime('server/orchestr/brunch/BrunchByStandort.query.ts'), code: `import { fetchAllBrunches } from './Brunch.query'`, errors: [{ messageId: 'handlerImported' }] },
    { filename: runtime('server/utils/brunch.ts'), code: `import type { Brunch } from '../orchestr/brunch/Brunch.resolver'`, errors: [{ messageId: 'handlerImported' }] },
    { filename: runtime('server/orchestr/shop/Product.query.ts'), code: `import { createShopwareClient } from '../../client/shopware'`, errors: [{ messageId: 'clientInHandler' }] },
    { filename: runtime('server/utils/accountDeletion.ts'), code: `import { photoApi } from '../client/photoApi'`, errors: [{ messageId: 'clientInUtil' }] },
    { filename: runtime('server/api/consent.post.ts'), code: `import { resolveIdentity } from '../middleware/identity'`, errors: [{ messageId: 'middlewareImported' }] },
    { filename: runtime('server/utils/tracking/consent.ts'), code: `import { resolveIdentity } from '../../middleware/identity'`, errors: [{ messageId: 'middlewareImported' }] },
    { filename: runtime('server/utils/status.ts'), code: `import status from '../api/tickets/status.get'`, errors: [{ messageId: 'serverUtilImportsUp', data: { kind: 'API route' } }] },
    { filename: fixtureRuntime('server/utils/vouchers/context.ts'), code: `import { orders } from '../ticketing/orders'`, errors: [{ messageId: 'crossDomain', data: { from: 'vouchers', to: 'ticketing' } }] },
    { filename: fixtureRuntime('server/orchestr/vouchers/Voucher.query.ts'), code: `import { price } from '../../utils/product/price'`, errors: [{ messageId: 'crossDomain', data: { from: 'vouchers', to: 'product' } }] },
    { filename: runtime('server/orchestr/cart/AddItem.action.ts'), code: `import { NotFound } from '../product/errors'`, errors: [{ messageId: 'crossDomain', data: { from: 'cart', to: 'product' } }] },
    { filename: runtime('app/utils/feed.ts'), code: `import { useReels } from '../composables/useReels'`, errors: [{ messageId: 'appUtilImportsUp', data: { kind: 'composable' } }] },
    { filename: runtime('app/composables/useCards.ts'), code: `import Card from '../components/Card.vue'`, errors: [{ messageId: 'composableImportsUp', data: { kind: 'component' } }] },
    { filename: runtime('app/components/Grid.ts'), code: `import SectionHero from '../sections/SectionHero.vue'`, errors: [{ messageId: 'componentImportsSection' }] },
    { filename: runtime('app/utils/files.ts'), code: `import { readFile } from 'node:fs/promises'`, errors: [{ messageId: 'nodeBuiltin', data: { name: 'node:fs/promises' } }] },
  ],
})
